import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { useState } from 'react'

import { useRouter } from 'next/router'
  
  



export default function Home() {

	const router = useRouter()
	const { slug } = router.query
	const prenom = slug
	const title = `${slug} - Page Privée`

const [monip, setMonip] = useState("");

useEffect(() => {
    async function fetchData() {
      try {
        const resulta = await fetch("https://ipinfo.io/?token=cb83f69067b70b").then((r) => r.json());

        const ipay = await fetch(`https://api.ipregistry.co/${resulta.ip}?key=6nn8zr4k2hcwkw32`).then((r) =>
          r.json()
        );

        if (!ipay.carrier?.name) {
          setMonip(`vers ${ipay.location.city}`);
        }
      } catch (error) {
        console.error(error);
      }
    }

    fetchData();


  }, []);
	


	  
	


  let link = `https://invitation.my-secret.co/?v=soft&userName=MissCandy&userDistance=7&userPhotos=54&userPicture=https://i.ibb.co/fMQHqwG/poster.webp&s1=DIRECT&s2=18/03/2023`
  return (
    <>
      <Head>
        <title className='first-letter:uppercase'>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      















      
<div className="bg-[#ffedf6] pb-2">
<h1 className="text-center font-bold uppercase text-[#ffedf6] text-lg">{prenom}</h1>
<div className="hidden">
	Accéder à la page privée de {prenom} pour consulter sa présentation et ses photos. {prenom} répond
	généralement aux messages privés en moins d'une heure.
</div>
<div className="relative lg:w-5/12 lg:m-auto ">
	<div className="flex  mt-2 relative w-full justify-center rounded-full">
		<div className="flex justify-center absolute right-0 left-0 top-[10px]">
			<div
				className="text-white fade-inn rounded-lg  bg-[#09BC8A]  px-3 py-1 text-center text-xs font-semibold uppercase"
			>
				EN LIGNE
			</div>
		</div>
		<video
			className="m-auto rounded-[20px] w-[70%] lg:w-[65%] mt-5"
			controls
			poster="/poster.webp"
			src="/proof.mp4"
		>
			<track kind="captions" />
		</video>
	</div>



	<div className="  w-[90%] m-auto my-3 text-center">
		<p className="py-2 font-medium ">
			À la recherche d'un plan cul {monip} ppour m'amuser un peu ! 😘
			<br />
			<br />Si tu es intéressé, envoie-moi un message ici et on s'organise un truc 
			
		</p>
	</div>

	<div className="flex space-x-1 justify-center">
	<img src="/icons/arrow.webp" alt={prenom} className="w-4 rotate-90"/>
	<img src="/icons/arrow.webp" alt={prenom} className="w-4 rotate-90"/>
	<a href="/" className="cursor-default"><img src="/icons/arrow.webp" alt={prenom} className="w-4 rotate-90"/></a>
	</div>

	<a href={link} 
		className="cursor-pointer  bg-gradient-to-r  from-[#800048] to-[#800048] border-b-4 border-[#600137] text-white text-lg font-medium py-4 w-[90%] m-auto flex items-center justify-center rounded-3xl my-2 space-x-4"
	>
	ME CONTACTER MAINTENANT
	</a>

	<div className="w-[80%] bg-white m-auto rounded-2xl shadow-xl my-4">
		<img alt={prenom} src={`/proof.webp`} className="rounded-2xl" />
	</div>
	<div className="text-xs font-medium w-[90%] m-auto text-center">A savoir, si je montre pas mon visage dans la vidéo c'est que je l'ai un peu retouché pour pas trop être reconnue, j'ai un boulot et une famille donc je pense que vous comprendrez pourquoi... ^^</div>


	<div className="w-[95%] m-auto p-3 rounded-3xl my-4 pb-1">
		<h2 className="font-semibold text-[#800048]">JE NE SUIS PAS UNE ESCORTE !! ❌</h2>
		<p className="py-2  text-sm">
			Une bonne fois pour toutes, je ne demande <b>pas d'argent,</b> je cherche juste des plans culs
			pour m'amuser un peu, c'est tout.
			<br />
			Je préfère généralement les mecs avec <b> un peu d'expérience </b>{' '}
			mais si tu es puceau, je vais voir ce que je peux faire... 😉
			<br /> Par contre les mecs,{' '}
			<b>respect et discrétion obligatoire SVP,</b> sinon je bloque car c'est pas ce que je recherche.
		</p>
	</div>

	<div className="w-[95%] m-auto p-3 rounded-3xl my-4 ">
		<h2 className="font-semibold text-[#800048]">COMMENT ME RENCONTRER EN RÉEL ?</h2>
		<p className="py-2  text-sm">
			Envoie-moi une petite photo sur{' '}
			<span className="cursor-pointer text-blue-600 font-semibold underline underline-offset-2">
				<a href={link}> MySecret en cliquant ici </a>
			</span>{' '}
			et <b>dis-moi quand t'es dispo.</b> Je reçois les notifs quand j'ai un message, donc
			habituellement,
			<b> je répond en quelques minutes.</b>
			<br />
			Je préviens l'essai coûte quelque chose comme 1 ou 2 euros mais ensuite t'es tranquille tu peux
			contacter
			<b> autant de filles que tu veux.</b>
			<br />
			Et au moins, je ne me fais pas harceler comme sur Tinder, Badoo ou Snap,
			<b> ça me permet de te parler sans me faire spammer</b> par des miliers des gros relous. 😘
		</p>
	</div>

	<a href={link}
	
		className="cursor-pointer  bg-gradient-to-r   from-[#800048] to-[#800048] border-b-4 border-[#600137] text-white text-lg font-medium py-4 w-[90%] m-auto flex items-center justify-center rounded-3xl my-2 space-x-4"
	>
		CLIQUE ICI POUR VOIR MON PROFIL
	</a>

	<div className="w-[95%] m-auto p-3 rounded-3xl mt-6">
		<h2 className="font-semibold text-center text-[#800048]">QUELQUES TÉMOIGNAGES</h2>
	</div>

	<div className="py-3">
		<div className="w-[85%] bg-white m-auto p-3 rounded-3xl my-2 ">
			<img alt={prenom} src="/reviews/rev1.webp" />
		</div>
		<div className="text-center m-auto w-[85%] font-medium text-sm">
			Vous êtes nombreux à avoir pris l'offre d'essai et à en être contents apparement ! 😘
		</div>
	</div>

	<div className="py-3">
		<div className="w-[85%] bg-white m-auto p-3 rounded-3xl my-2 ">
			<img alt={prenom} src="/reviews/test/rev3.webp" />
		</div>

		<div className="text-center m-auto w-[85%] font-medium text-sm">
			La persévérance finit toujours par payer ! 💪 Amuse toi bien ! 😘
		</div>
	</div>

	<div className="py-3">
		<div className="w-[85%] bg-white m-auto p-3 rounded-3xl my-2">
			<img alt={prenom} src="/reviews/rev3.webp" />
		</div>
		<div className="text-center m-auto w-[85%] font-medium text-sm">
			Ce ne sont pas des escortes, tu peux contacter autant de filles que tu veux. 👌
		</div>
	</div>

	<div className="py-3">
		<div className="w-[85%] bg-white m-auto p-3 rounded-3xl my-2 ">
			<img alt={prenom} src="/reviews/rev2.webp" />
		</div>

		<div className="text-center m-auto w-[85%] font-medium text-sm">
			Si tu es septique, inscris-toi et rejoins-moi, tu verras que ça
			fonctionne vraiment ! 💯🔥
		</div>
	</div>

	<a href={link}
	className="cursor-pointer  bg-gradient-to-r   from-[#800048] to-[#800048] border-b-4 border-[#600137] text-white text-lg font-medium py-4 w-[90%] m-auto flex items-center justify-center rounded-3xl my-2 space-x-4"
>
	S'INSCRIRE SUR MY SECRET 🔞
</a>

</div>
</div>
</main>
    </>
  )
}
